@startuml
skinparam conditionStyle inside
title Алгоритм системы "Колобок" (Маршрутизация и безопасность)

start

:Колобок появляется;
:Колобок: сбежать от Деда и Бабы;

if (Заяц пытается съесть?) then (да)
    if (Колобок поёт песню?) then (да)
        :Заяц обманут;
        :Колобок продолжает путь;
    else (нет)
        :Колобок съеден Зайцем; <<#lightgreen>>
        stop
    endif
else (нет)
    :Колобок продолжает путь;
endif

if (Волк пытается съесть?) then (да)
    if (Колобок поёт песню?) then (да)
        :Волк обманут;
        :Колобок продолжает путь;
    else (нет)
        :Колобок съеден Волком; <<#lightgreen>>
        stop
    endif
else (нет)
    :Колобок продолжает путь;
endif

if (Медведь пытается съесть?) then (да)
    if (Колобок поёт песню?) then (да)
        :Медведь обманут;
        :Колобок продолжает путь;
    else (нет)
        :Колобок съеден Медведем; <<#lightgreen>>
        stop
    endif
else (нет)
    :Колобок продолжает путь;
endif

partition "Внешнее прерывание - Лиса" {
    :Лиса пытается съесть Колобка;
    if (Колобок поёт песню?) then (да)
        :Лиса: подменитьПараметрыСлуха();
        if (Подмена удалась?) then (да)
            :Колобок съеден Лисой!; <<#lightgreen>>
            stop
        else (нет)
            :Колобок продолжает путь;
        endif
    else (нет)
        :Колобок съеден Лисой!; <<#lightgreen>>
        stop
    endif
}

:Колобок успешно сбежал от всех!; <<#lightgreen>>
stop

@enduml
